---
- hosts: all
  sudo: true
  roles:
   - common

- hosts: compute
  vars_files:
    - credentials.yml
  sudo: true
  roles:
    - compute

# - hosts: controller
#   vars_files:
#     - credentials.yml
#   sudo: true
#   roles:
#     - controller
