- name: install MariaDB
  yum:
    name: mariadb
    state: present

- name: install MariaDB-Server
  yum:
    name: mariadb-server
    state: present

- name: install PyMySQL (python2)
  yum:
    name: python2-PyMySQL
    state: present

- name: Install the Python MySQL Support Libraries
  yum:
    name: MySQL-python

- name: install pip
  yum:
    name: python-pip

- name: Install pexpect
  pip:
    name: pexpect

- name: modify MariaDB file
  template:
    src=mariadb.j2
    dest=/etc/my.cnf.d/openstack.cnf

- name: start database service (1/2)
  shell: systemctl enable mariadb.service

- name: start database service (2/2)
  shell: systemctl start mariadb.service

- name: create ~/.my.conf file with root user
  template:
    src: root.cnf.j2
    dest: /root/.my.cnf

# This is taken from https://injustfiveminutes.wordpress.com/2014/08/25/ansible-mysql_secure_installation-playbook/
# TARGET: Ensure IDEMPOTENCY  of mariadb et al
# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: Change root user password on first run
  mysql_user:
    login_user: root
    login_password: vagrant
    name: root
    password: vagrant
    host: "{{ item }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: _secure_ database (CHECK BEFORE USE)
  expect:
    command: mysql_secure_installation
    echo: yes
    responses:
        '(enter for none)': 'vagrant'
        'Y/n' : 'n'
