- name: install MariaDB
  yum:
    name: mariadb
    state: present

- name: install MariaDB-Server
  yum:
    name: mariadb-server
    state: present

- name: install PyMySQL (python2)
  yum:
    name: python2-PyMySQL
    state: present

- name: Install the Python MySQL Support Libraries
  yum:
    name: MySQL-python

- name: install pip
  yum:
    name: python-pip

- name: Install pexpect
  pip:
    name: pexpect


- name: modify MariaDB file
  template:
    src=mariadb.j2
    dest=/etc/my.cnf.d/openstack.cnf

- name: start database service
  service:
    name: mariadb.service
    state: started

# - name: start database service (2/2)
#   shell: systemctl start mariadb.service

# This is taken from https://injustfiveminutes.wordpress.com/2014/08/25/ansible-mysql_secure_installation-playbook/
# TARGET: Ensure IDEMPOTENCY  of mariadb et al
- name: Check if .my.cnf exists
  stat:
    path: /root/.my.cnf
  register: root_credentials

- name: Secure database if .my.cnf does not exist
  expect:
    command: mysql_secure_installation
    responses:
        'Enter current password for root' : ''
        'Set root password' : 'Y'
        'New password' : "{{ mysql_password }}"
        'enter new password' : "{{ mysql_password }}"
        'Remove anonymous' : 'Y'
        'Disallow root' : 'Y'
        'Remove test' : 'Y'
        'Reload privilege' : 'Y'
  when: root_credentials.stat.exists==False

- name: copy .my.cnf file with root password credentials if doesnt exist
  template:
    src: root_credentials.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  when: root_credentials.stat.exists==False
