- name: install Memcached
  yum:
   name: memcached
   state: present

- name: install python-memcached
  yum:
   name: python-memcached
   state: present

- name: enable acces via management network
  template:
    src=memcached.j2
    dest=/etc/sysconfig/memcached

- name: start memcached service
  service:
    name: memcached
    state: started
