# - name: conecting to database acces client
#   service:
#     name: mariadb
#     state: started
- name: creating keystone database
  mysql_db:
    name: keystone
    login_user: root
    login_password: vagrant
    state: present

- name: set privileges root
  mysql_user:
    append_privs: yes
    login_user: root
    login_password: vagrant
    user: root
    priv: 'keystone.*:ALL,GRANT'
    state: present

- name: Installing packages that keystone needs
  yum:
    name: "{{ item }}"
  with_items:
    - openstack-keystone
    - httpd
    - mod_wsgi

- name: modify /etc/keystone/keystone.conf (CAREFUL PASSWORD)
  lineinfile:
   path: /etc/keystone/keystone.conf
   regexp: '^\[database\]$'
   insertafter: '^\[database\]$'
   line: 'connection = mysql+pymysql://keystone:vagrant@controller/keystone'
   state: present

- name: modify provider (use fernet) in /etc/keystone/keystone.conf
  lineinfile:
   path: /etc/keystone/keystone.conf
   regexp: '^\[token\]$'
   insertafter: '^\[token\]$'
   line: 'provider = fernet'
   state: present

# This is related to create user and set privileges block ....?
# - name: populate Identity service databse
#   expect:
#     command: keystone-manage db_sync
#     responses:
#       keystone

# - name: Initialize fernet repositories
#   shell:
