- name: creating neutron database
  mysql_db:
    name: neutron
    login_user: root
    login_password: "{{ mysql_password }}"
    state: present

- name: set privileges neutron
  mysql_user:
    append_privs: yes
    login_user: root
    login_password: "{{ mysql_password }}"
    user: neutron
    password: "{{ neutron_password }}"
    priv: 'neutron.*:ALL'
    host: "{{ item }}"
    state: present
  with_items:
    - localhost
    - '%'

- name: check if user neutron exists
  shell: " source /home/admin-openrc && openstack user show neutron"
  register: u_neutron_result
  ignore_errors: True
  no_log: True

- name: check if compute service exists
  shell: source /home/admin-openrc && openstack service show network
  register: network_service_exists
  ignore_errors: True
  no_log: True


- name: create neutron user
  shell: "source /home/admin-openrc && openstack user create --domain default --password {{ neutron_password }} neutron"
  when: u_neutron_result is failed

- name: add admin role to neutron user
  shell: "source /home/admin-openrc && openstack role add --project service --user neutron admin"
  when: u_neutron_result is failed

- name: create neutron service entity
  shell: "source /home/admin-openrc && openstack service create --name neutron network" #--description \"OpenStack Networking\"
  when: network_service_exists is failed

- name: create neutron service API endpoints
  shell: "source /home/admin-openrc &&  openstack endpoint create --region RegionOne  network {{ item }} http://{{ controller_ip }}:9696"
  with_items:
    - public
    - internal
    - admin

# Here configure  which of the two services will be used
- name: Installing Self-service networks components
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge
    - ebtables

- name: Neutron configuration file
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf

- name: Modular Layer 2 configuration
  template:
    src: ml2_config.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini

- name: Linux bridge agent configuration
  template:
    src: linux_bridge.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: layer3 agent configuration
  template:
    src: layer_3.j2
    dest: /etc/neutron/l3_agent.ini

- name: configure DHCP agent
  template:
    src: dhcp_config.j2
    dest: /etc/neutron/dhcp_agent.ini
###############################################################

- name:  copy neutron.conf
  template:
   src: metadata_agent.j2
   dest: /etc/neutron/metadata_agent.ini

- name: Create symbolic link Neutron
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link

- name: Populate database
  shell: "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head"
  become: true
  become_user: neutron

- name: Restart Compute API service
  service:
    name: openstack-nova-api
    state: restarted

- name: Start networking service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
