---
- name: yumming centos-release-openstack-queens
  yum:
   name: centos-release-openstack-queens

- name: replace QEMU-EC.repo
  copy:
    src: ../files/CentOS-QEMU-EV.repo
    dest: /etc/yum.repos.d/

- name: upgrade packages
  yum:
    name: '*'

- name: install openstack client
  yum:
   name: python-openstackclient

- name: install selinux
  yum:
   name: openstack-selinux
